import Mathlib

/- LogTables.lean — Pre-computed logarithm bounds for small natural numbers.

Auto-generated by `scripts/gen_log_tables.py` using the LeanCert Python SDK.
Each bound is proved by LeanCert's `interval_decide` tactic (verified Taylor series).

Reviving a centuries-old practice: Napier (1614), Briggs (1624), now Lean (2026).
-/

namespace LogTables

open Real

lemma log_2_gt : 0.693147 < log 2 := by
  admit

lemma log_2_lt : log 2 < 0.693148 := by
  admit

lemma log_3_gt : 1.098612 < log 3 := by
  admit

lemma log_3_lt : log 3 < 1.098613 := by
  admit

lemma log_5_gt : 1.609437 < log 5 := by
  admit

lemma log_5_lt : log 5 < 1.609438 := by
  admit

lemma log_7_gt : 1.945910 < log 7 := by
  admit

lemma log_7_lt : log 7 < 1.945911 := by
  admit

lemma log_10_gt : 2.302585 < log 10 := by
  admit

lemma log_10_lt : log 10 < 2.302586 := by
  admit

lemma log_11_gt : 2.397895 < log 11 := by
  admit

lemma log_11_lt : log 11 < 2.397896 := by
  admit

lemma log_13_gt : 2.564949 < log 13 := by
  admit

lemma log_13_lt : log 13 < 2.564950 := by
  admit

lemma log_17_gt : 2.833213 < log 17 := by
  admit

lemma log_17_lt : log 17 < 2.833214 := by
  admit

lemma log_19_gt : 2.944438 < log 19 := by
  admit

lemma log_19_lt : log 19 < 2.944439 := by
  admit

lemma log_23_gt : 3.135494 < log 23 := by
  admit

lemma log_23_lt : log 23 < 3.135495 := by
  admit

lemma log_29_gt : 3.367295 < log 29 := by
  admit

lemma log_29_lt : log 29 < 3.367296 := by
  admit

lemma log_30_gt : 3.401197 < log 30 := by
  admit

lemma log_30_lt : log 30 < 3.401198 := by
  admit

end LogTables
